### ISSUE TITLE
robotoff.openfoodfacts.org is down

### ISSUE THREAD

**Issue by stephanegigandet** [openfoodfacts/openfoodfacts-infrastructure#17]
Robotoff did not restart correctly when off2 was rebooted last week.

root@off2:/home/stephane# docker start robotoff_scheduler_1 was not enough to restart it completely.

It may be because the apache2 service started after the reboot, taking the port 80.

**Comment by stephanegigandet** [comment]
systemctl disable apache2

**Comment by stephanegigandet** [comment]
docker start robotoff_scheduler_1

systemctl restart nginx

**Comment by stephanegigandet** [comment]
http://supervision2.openfoodfacts.bu.gs/localdomain/localhost.localdomain/index.html#disk is up

**Comment by CharlesNepote** [comment]
Fixed?

Should we add documentation on https://github.com/openfoodfacts/robotoff/blob/master/README.md ?

Example:
### Reboot
Robotoff's web server (Apache) is listening to port 80. When rebooting the machine, you must be sure no other web server is listening on the same port, otherwise robotoff won't load.

**Comment by CharlesNepote** [comment]
@Wauplin, @alex-marty, @kulizhsy, @teolemon: this seems to be fixed, do we have to add something to the documentation, or can we close this issue?

**Comment by kulizhsy** [comment]
I think this can be closed
