### ISSUE TITLE
Daily Quality Email >> Deep link into editing

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-infrastructure#261]
### What
- Daily Quality Email >> Deep link into editing
- Going from https://world.openfoodfacts.org/cgi/product.pl?type=edit&code=0581740005956
- to https://world.openfoodfacts.org/cgi/product.pl?type=edit&code=0581740005956#nutrition

**Comment by teolemon** [comment]
cc @CharlesNepote

**Comment by CharlesNepote** [comment]
The problem is that some issues are related to ingredients and not nutrition. For the moment there are few Data Quality Errors related to ingredients but I expect that there will be far more in the following weeks.

For 3 products a day, this is not very difficult to click on [Ingredients] or [Nutrition] button on the nav bar:
![image](https://github.com/openfoodfacts/openfoodfacts-infrastructure/assets/562352/727c3a8d-dcd9-4579-8091-d10adb552e6f)

Don't hesitate to [register](https://mirabelle.openfoodfacts.org/-/data-quality-daily/subscribe) to test it ;-)
