### ISSUE TITLE
Dev MongoDB VM

### ISSUE THREAD

**Issue by ocervell** [openfoodfacts/openfoodfacts-infrastructure#45]
[All the following limits (RAM, CPU, storage) can be dynamically adjusted later.]

### OS
Debian last stable

### Local disk space
40GB

### RAM
4GB (tentative)

### Nb of CPU
2

### Main software bricks
MongoDB running in Docker

### Usage
Dev MongoDB database.

### Machine administrators
ocervell
cquest
stephane
pierre
yana

**Comment by cquest** [comment]
Container created, with nesting/keyctl options.

Is ssh bounce ok for you ?

**Comment by CharlesNepote** [comment]
Why use Mongo inside docker if it's on a different container? Installing mongo from command line is far more simple and lower the barrier to system administration (vanilla Debian). We have a standardized way to install Mongo on OFF infra: https://gist.github.com/CharlesNepote/13198c2ed336fc64cb674d63876e8d99

Docker creates an additional dependency, and most of the core team is not very comfortable with docker. Docker on a container also creates two levels of virtualization, which probably impacts performance, not just complexity. I can understand docker for some kind of usages, but I'm not comfortable with it for a single task server.

**Comment by ocervell** [comment]
To be fair I was more in favour to keep the MongoDB deployment as part of Product Opener Docker deployment, to avoid weird dependency issues between deployments. I'm not sure I understand the full rationale behind moving the db to a separate Proxmox container.

That said, I think running in Docker fixes three of the biggest issue we have in the infrastructure world, e.g **traceability of deployments**, **repeatability of deployments** and **idempotency**.  It will make it easier to do version updates, and doesn't pollute the Proxmox container (long-term drift).

Eventually since the PO dev environment already runs in Docker we should have educational sessions with the core team on how to use it properly.

**Comment by ocervell** [comment]
That said I fully agree than running Docker for one service is overkill.

**Comment by stephanegigandet** [comment]
I think mongodb in docker for local dev environment makes a lot of sense, so that it's very easy to get a dev environment with everything. We install mongo, we can install 100 products, and that's all we need.

For preprod (openfoodfacts.net), the "public" development server (openfoodfacts.dev), and for production (openfoodfacts.org), the requirements are different though: we want a permanent mongodb database, with all products (or a copy of all products). We do not want to build, stop, start etc. this database whenever the Product Opener code is deployed. That's why I suggested that we have 1 shared mongodb "preprod" + "public dev" container, that has one database that can be used by openfoodfacts.net and openfoodfacts.org. MongoDB eats a lot of ressources, so I think it makes sense to have just one for .net and .dev

So as the mongodb setup etc. should not change, we don't have to run it through docker for this container I think.
